// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5LZWZIeVXqan3kkzzIXur-1sdFrK0Sk',
    appId: '1:325499269042:web:6f10116bc275b6b876feab',
    messagingSenderId: '325499269042',
    projectId: 'scope-guard-290a0',
    authDomain: 'scope-guard-290a0.firebaseapp.com',
    databaseURL: 'https://scope-guard-290a0-default-rtdb.firebaseio.com',
    storageBucket: 'scope-guard-290a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkzaAPNBBYqXfVjOGNLYE6BUH0Roqc0M',
    appId: '1:325499269042:android:4bc83110ce850e8776feab',
    messagingSenderId: '325499269042',
    projectId: 'scope-guard-290a0',
    databaseURL: 'https://scope-guard-290a0-default-rtdb.firebaseio.com',
    storageBucket: 'scope-guard-290a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQedUdQrBrBixcf7QwMtAAe9rIrHyBPk',
    appId: '1:325499269042:ios:45898638803e218676feab',
    messagingSenderId: '325499269042',
    projectId: 'scope-guard-290a0',
    databaseURL: 'https://scope-guard-290a0-default-rtdb.firebaseio.com',
    storageBucket: 'scope-guard-290a0.firebasestorage.app',
    iosBundleId: 'com.example.scopeGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQedUdQrBrBixcf7QwMtAAe9rIrHyBPk',
    appId: '1:325499269042:ios:45898638803e218676feab',
    messagingSenderId: '325499269042',
    projectId: 'scope-guard-290a0',
    databaseURL: 'https://scope-guard-290a0-default-rtdb.firebaseio.com',
    storageBucket: 'scope-guard-290a0.firebasestorage.app',
    iosBundleId: 'com.example.scopeGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5LZWZIeVXqan3kkzzIXur-1sdFrK0Sk',
    appId: '1:325499269042:web:aace26432bed991b76feab',
    messagingSenderId: '325499269042',
    projectId: 'scope-guard-290a0',
    authDomain: 'scope-guard-290a0.firebaseapp.com',
    databaseURL: 'https://scope-guard-290a0-default-rtdb.firebaseio.com',
    storageBucket: 'scope-guard-290a0.firebasestorage.app',
  );
}
