import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../requests/data/request_model.dart';

class ReportService {
  ReportService._();
  static final ReportService instance = ReportService._();

  Future<Uint8List> generateScopeReport({
    required String clientName,
    required List<RequestModel> requests,
  }) async {
    final pdf = pw.Document();

    final outOfScope = requests.where((r) => !r.inScope).toList();
    final total = outOfScope.fold<int>(
      0,
      (sum, r) => sum + (r.estimatedCost ?? 0),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        footer: (ctx) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Generated by Scope Guard • Page ${ctx.pageNumber}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ),
        build: (_) => [
          _header(clientName),
          pw.SizedBox(height: 20),
          _summary(outOfScope.length, total),
          pw.SizedBox(height: 24),
          _table(outOfScope),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _header(String clientName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Scope Creep Report',
          style: pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Text('Client: $clientName', style: const pw.TextStyle(fontSize: 12)),
        pw.SizedBox(height: 4),
        pw.Text(
          'Generated on: ${DateTime.now()}',
          style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      ],
    );
  }

  pw.Widget _summary(int count, int total) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey200,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Out-of-scope requests: $count',
            style: const pw.TextStyle(fontSize: 12),
          ),
          pw.Text(
            'Total extra cost: ₹$total',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  pw.Widget _table(List<RequestModel> rows) {
    if (rows.isEmpty) {
      return pw.Text(
        'No out-of-scope requests found.',
        style: pw.TextStyle(color: PdfColors.grey700),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(4),
        2: const pw.FlexColumnWidth(1.5),
      },
      children: [_tableHeader(), ...rows.map(_tableRow)],
    );
  }

  pw.TableRow _tableHeader() {
    return pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.grey300),
      children: [
        _cell('Title', bold: true),
        _cell('Description', bold: true),
        _cell('Cost', bold: true, alignRight: true),
      ],
    );
  }

  pw.TableRow _tableRow(RequestModel r) {
    return pw.TableRow(
      children: [
        _cell(r.title),
        _cell(r.description),
        _cell(
          r.estimatedCost != null ? '₹${r.estimatedCost}' : '—',
          alignRight: true,
        ),
      ],
    );
  }

  pw.Widget _cell(String text, {bool bold = false, bool alignRight = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        maxLines: 3,
        overflow: pw.TextOverflow.clip,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
        textAlign: alignRight ? pw.TextAlign.right : pw.TextAlign.left,
      ),
    );
  }
}
